Repository knative/client-contrib, pull requests merged in 2020-07, with the labels that each got.

#62 Improve domain subcommands and some wording suggestions
  plugins/admin/README.adoc
  plugins/admin/core/root.go
  plugins/admin/core/root_test.go
  plugins/admin/pkg/command/autoscaling/autoscaling.go
  plugins/admin/pkg/command/autoscaling/update.go
  plugins/admin/pkg/command/domain/domain.go
  plugins/admin/pkg/command/domain/set.go
  plugins/admin/pkg/command/domain/set_test.go
  plugins/admin/pkg/command/domain/unset.go
  plugins/admin/pkg/command/registry/add.go
  plugins/admin/pkg/command/registry/registry.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#64 [source-kafka] Fix error handling for kubeconfig
  plugins/source-kafka/OWNERS
  plugins/source-kafka/go.mod
  plugins/source-kafka/go.sum
  plugins/source-kafka/pkg/client/client.go
  plugins/source-kafka/pkg/client/client_fake.go
  plugins/source-kafka/pkg/client/client_test.go
  plugins/source-kafka/pkg/factories/boilerplate.go
  plugins/source-kafka/pkg/factories/boilerplate_test.go
  plugins/source-kafka/pkg/factories/command_factory.go
  plugins/source-kafka/pkg/factories/command_factory_test.go
  plugins/source-kafka/pkg/factories/flags_factory.go
  plugins/source-kafka/pkg/factories/flags_factory_test.go
  plugins/source-kafka/pkg/factories/rune_factory.go
  plugins/source-kafka/pkg/factories/rune_factory_test.go
  plugins/source-kafka/pkg/factories/source_factory.go
  plugins/source-kafka/pkg/factories/source_factory_test.go
  plugins/source-kafka/pkg/types/interfaces.go
  plugins/source-kafka/vendor/github.com/maximilien/kn-source-pkg/pkg/client/client.go
  plugins/source-kafka/vendor/github.com/maximilien/kn-source-pkg/pkg/factories/boilerplate.go
  plugins/source-kafka/vendor/github.com/maximilien/kn-source-pkg/pkg/factories/kn_source_factory.go
  plugins/source-kafka/vendor/github.com/maximilien/kn-source-pkg/pkg/factories/rune_factory.go
  plugins/source-kafka/vendor/github.com/maximilien/kn-source-pkg/pkg/types/interfaces.go
  plugins/source-kafka/vendor/github.com/maximilien/kn-source-pkg/pkg/types/typesfakes/fake_kn_source_factory.go
  plugins/source-kafka/vendor/github.com/maximilien/kn-source-pkg/pkg/types/typesfakes/fake_run_efactory.go
  plugins/source-kafka/vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#65 [source-kafka] Fix subcommand's long, short, Use values and update docs
  plugins/source-kafka/README.md
  plugins/source-kafka/docs/header.md
  plugins/source-kafka/pkg/client/client.go
  plugins/source-kafka/pkg/factories/command_factory.go
  plugins/source-kafka/pkg/factories/rune_factory.go
Labels: approved, cla: yes, lgtm, size/M
