Repository knative/client-contrib, pull requests merged in 2020-06, with the labels that each got.

#38 kn-admin domain unset command
  plugins/admin/README.adoc
  plugins/admin/pkg/command/domain/domain.go
  plugins/admin/pkg/command/domain/domain_test.go
  plugins/admin/pkg/command/domain/unset.go
  plugins/admin/pkg/command/domain/unset_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#36 Update go.mod to specify the module is go1.14
  go.mod
  go.sum
  plugins/admin/go.mod
  plugins/admin/hack/build.sh
  plugins/admin/vendor/modules.txt
  plugins/hello/go.mod
  plugins/hello/hack/build.sh
  plugins/hello/test/presubmit-tests.sh
  plugins/hello/vendor/modules.txt
  plugins/migration/go.mod
  plugins/migration/hack/build.sh
  plugins/migration/test/presubmit-tests.sh
  plugins/migration/vendor/modules.txt
  plugins/source-kafka/go.mod
  plugins/source-kafka/hack/build.sh
  plugins/source-kafka/vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#45 Update test-infra to stop using serving.yaml
  scripts/test-infra/library.sh
Labels: approved, cla: yes, lgtm, size/S

#50 Update cluster-setup to compile kn properly
  go.mod
  go.sum
  plugins/hello/go.mod
  plugins/hello/go.sum
  plugins/hello/vendor/github.com/spf13/cobra/README.md
  plugins/hello/vendor/github.com/spf13/cobra/args.go
  plugins/hello/vendor/github.com/spf13/cobra/bash_completions.go
  plugins/hello/vendor/github.com/spf13/cobra/bash_completions.md
  plugins/hello/vendor/github.com/spf13/cobra/command.go
  plugins/hello/vendor/github.com/spf13/cobra/custom_completions.go
  plugins/hello/vendor/github.com/spf13/cobra/fish_completions.go
  plugins/hello/vendor/github.com/spf13/cobra/fish_completions.md
  plugins/hello/vendor/modules.txt
  test/common.sh
Labels: approved, cla: yes, lgtm, size/XXL

#47 [kn-admin]Add support to remove registry with credentials
  plugins/admin/README.adoc
  plugins/admin/pkg/command/autoscaling/update.go
  plugins/admin/pkg/command/autoscaling/update_test.go
  plugins/admin/pkg/command/registry/add.go
  plugins/admin/pkg/command/registry/add_test.go
  plugins/admin/pkg/command/registry/registry.go
  plugins/admin/pkg/command/registry/registry_test.go
  plugins/admin/pkg/command/registry/remove.go
  plugins/admin/pkg/command/registry/remove_test.go
  plugins/admin/pkg/types.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#40 [kn-admin]Added utils to update configmap
  plugins/admin/README.adoc
  plugins/admin/pkg/command/autoscaling/autoscaling.go
  plugins/admin/pkg/command/autoscaling/update.go
  plugins/admin/pkg/command/autoscaling/update_test.go
  plugins/admin/pkg/command/domain/domain.go
  plugins/admin/pkg/command/domain/set.go
  plugins/admin/pkg/command/domain/set_test.go
  plugins/admin/pkg/command/domain/unset.go
  plugins/admin/pkg/command/domain/unset_test.go
  plugins/admin/pkg/command/registry/add.go
  plugins/admin/pkg/command/registry/registry.go
  plugins/admin/pkg/command/utils/utils.go
  plugins/admin/pkg/command/utils/utils_test.go
  plugins/admin/vendor/k8s.io/apimachinery/pkg/util/wait/doc.go
  plugins/admin/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go
  plugins/admin/vendor/k8s.io/client-go/util/retry/OWNERS
  plugins/admin/vendor/k8s.io/client-go/util/retry/util.go
  plugins/admin/vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XL
